autopkg/apizz-recipes

Shure_Wireless_Workbench/ShureWirelessWorkbench6.download.recipe
Shure updated their website and this recipe was failing due to that.  Good news, the file is consistent now.  Bad news, the version number is harder to find.  I updated the regex to match the link and version on the new website/file structure they have setup.
This is tested and working for me.
=> New regex to match link on new website

GeoGebra/GeoGebra6.download.recipe, GeoGebra/GeoGebraGeometry.download.recipe, GeoGebra/GeoGebraGraphingCalculator.download.recipe, Stage_Plot_Pro/StagePlotPro-5Place.download.recipe
Context: The [CodeSignatureVerifier](https://github.com/autopkg/autopkg/wiki/Using-CodeSignatureVerification) processor ensures that the downloaded applications/packages are signed by the expected developer certificate. Although this is not a guarantee that the payload is trouble-free, it's a good indicator that the file you downloaded is the one you intended to download.
=> Add CodeSignatureVerifier processor

SharedProcessors/unearthVersioner.py
In order to make your processors more compatible with AutoPkg running in Python 3, I've applied a few adjustments suggested by `python-modernize`, `pylint --py3k`, and `pylint` in general.
More adjustments may need to be made manually later, but this should catch the low-hanging fruit right now.
=> Basic python3 compatibility

Unity/Unity3DAndroidSupport.download.recipe, Unity/Unity3DAndroidSupport.munki.recipe, Unity/Unity3DAppleTVSupport.download.recipe, Unity/Unity3DAppleTVSupport.munki.recipe, Unity/Unity3DFacebookGamesSupport.download.recipe, Unity/Unity3DFacebookGamesSupport.munki.recipe, Unity/Unity3DLinuxSupport.download.recipe, Unity/Unity3DLinuxSupport.munki.recipe, Unity/Unity3DLuminSupport.download.recipe, Unity/Unity3DLuminSupport.munki.recipe, Unity/Unity3DWebGLSupport.download.recipe, Unity/Unity3DWebGLSupport.munki.recipe, Unity/Unity3DWindowsSupport.download.recipe, Unity/Unity3DWindowsSupport.munki.recipe, Unity/Unity3DiOSSupport.download.recipe, Unity/Unity3DiOSSupport.munki.recipe, Unity/Unity3DmacOSSupport.download.recipe, Unity/Unity3DmacOSSupport.munki.recipe
Add Unity component recipes given updates to [Unity3D.download.recipe](https://github.com/autopkg/joshua-d-miller-recipes/commit/414e8c82f11f46b349ac6f488959f2c867eb6777)
Munki recipes write version to text file in desired location, as pkg receipts all have a version of `0` and therefore won't install.  Achieved by utilizing the MunkiPkginfoMerger processor.
`postinstall_script` writes the receipt, `installcheck_script` verifies it's there and if not, or if the version collected is less than the latest available, installs it.
`update_for` ensures that these items are only associated with the same version of Unity3D.  `UNITY_MUNKI_ITEM_NAME` input variable allows you specify the name of the Unity item.
Ideally, want to eventually allow for more multiple`update_for` string items, but not …
=> Unity support component recipes

TeamViewer/TeamViewerHostCustom.pkg.recipe
Added version to package name to allow for minor version upgrades when deployed through Jamf Pro. Without this, Autopkg creates a package called Teamviewer.pkg and the jss_importer processor can never detect when there's a new package to upload because the name is always the same.
=> Added version to package name 

Epson/EpsonScannerDriverandScanUtility-NewCert.download.recipe
This parallels changes in my EpsonProDrivers.download recipe. Should be more flexible moving forward. Using the result_output_var_name should make it a little easier to read as well. Tested using Epson Expression 10000XL URL.
=> Update regex to accommodate HTML page change

CLEditor/YamahaCLEditor.download.recipe
Correct argument name is `strict_verification`. (https://github.com/autopkg/autopkg/wiki/Processor-CodeSignatureVerifier)
=> Adjust name of CodeSignatureVerifier argument

Lightwell/Lightwell.pkg.recipe, TeacherGaming/TeacherGaming.pkg.recipe
This pull request removes unused instances of `BUNDLE_ID` from recipe input variables, which will help reduce confusion by new AutoPkg users and simplify overrides created from this point on.
Making `BUNDLE_ID` available as an input variable is a common practice in AutoPkg recipes that use the [PkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-PkgCreator) processor ([example](https://github.com/autopkg/homebysix-recipes/blob/4fec9244a3af0f9b7c8f61f35a5cd7f4622fb162/soma-zone/LaunchControl.pkg.recipe#L40-L41)). It's likely that these recipes transitioned from PkgCreator to the more streamlined [AppPkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-AppPkgCreator) processor some time ago, but the now-unused input variable for `BUNDLE_ID` was never removed.
Recipe run …
=> Remove unused BUNDLE_ID input var

Google_Drive/GoogleDrive.munki.recipe, Google_Drive/GoogleDrive_app.munki.recipe
The Google Drive binary installs binaries with identifiers that include the arch `x86_64` or `arm64`. Munki continuously reinstalls the pkg since the pkginfo `receipts` array accounts for both of these architectures, however only one will ever be installed at a time. 
This MR sets the architecture-specific receipts as optional to avoid the loop behavior.
=> For Google Drive, set architecture-specific receipts to optional to avoid reinstall loop

Chrome_Remote_Desktop/ChromeRemoteDesktop.munki.recipe
The parent recipe has been copied to homebysix-recipes in order to prepare for cgerke-recipes deprecation. For details, see: https://github.com/autopkg/cgerke-recipes/issues/37
=> Change parent recipe for cgerke-recipes deprecation

VirtualBox/VirtualBox.munki.recipe, jss_helper/jss_helper.munki.recipe, yo/yo.munki.recipe
The sheagcraig-recipes repository is being deprecated (details here: https://github.com/autopkg/sheagcraig-recipes/issues/71). Many working and/or serviceable recipes have already been [copied](https://github.com/autopkg/homebysix-recipes/pull/414) to the homebysix-recipes repo. This PR changes the parent recipes in your repo to point to the homebysix-recipes version of any affected recipes.
In addition to updating trust info, users of the changed recipes will need to ensure the homebysix-recipes repo is added to their AutoPkg environment (`autopkg repo-add homebysix-recipes`).
=> Adjust parent recipes for sheagcraig-recipes repo deprecation

CrowdStrike/CrowdStrikeFalcon.munki.recipe
Munki will now check that the App itself is installed and not just pkg receipts.
Looks something like this.
```
<key>installs</key>
<array>
<dict>
<key>CFBundleIdentifier</key>
<string>com.crowdstrike.falcon.App</string>
<key>CFBundleName</key>
<string>Falcon</string>
<key>CFBundleShortVersionString</key>
<string>6.30</string>
<key>CFBundleVersion</key>
<string>143.01</string>
<key>minosversion</key>
<string>10.15</string>
<key>path</key>
<string>/Applications/Falcon.app</string>
<key>type</key>
<string>application</string>
<key>version_comparison_key</key>
<string>CFBundleShortVersionString</string>
</dict>
</array>
```
=> add Installs Array for Crowdstrike Falcon

SharedProcessors/ExecutableFileVersioner.py
As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/env python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …
=> Update Python path in processors to reflect changes in macOS 12.3+

CrowdStrike/CrowdStrikeFalcon.munki.recipe
As mentioned by this slack message: https://macadmins.slack.com/archives/CA9SU2FSS/p1669221316788909 
I confirmed that the 6.48 download only has the `com.crowdstrike.falcon.sensor.sysx` pkg id and has removed the others `com.crowdstrike.falcon.sensor.common` and `com.crowdstrike.falcon.sensor.kext` from the download.
=> as of v6.48 CS will no longer deploy the kext pkg

FileMaker/FileMakerProClaris.download.recipe
The download URL path structure has changed. This updates the default regex to support at least versions 19 and 20.
=> Update FileMakerProClaris.download.recipe to support v. 20

OpenKiosk/OpenKiosk.download.recipe
It's important to use HTTPS for downloading software whenever possible in order to avoid the possibility of person-in-the-middle attacks (like the one that affected the Sparkle update framework [in January 2016](https://vulnsec.com/2016/osx-apps-vulnerabilities/)).
For this pull request, I detected and changed to HTTPS URLs automatically using my [HTTPS Spotter](https://www.elliotjordan.com/posts/autopkg-https/) script, and then tested all changed recipes manually to ensure exit codes of recipe run remains the same before/after the change.
This PR was submitted using [Repo Lasso](https://github.com/homebysix/repo-lasso).
Thanks for considering!
=> Update all available URLs from HTTP to HTTPS

Karabiner-Elements/Karabiner-Elements.download.recipe, Karabiner-Elements/Karabiner-Elements.munki.recipe
Hi, @apizz 
This PR 
- Updates `CodeSignatureVerifier` in the download recipe with new App name
- Updates `MunkiInstallsItemsCreator` in the Munki recipe with new App name
Output from a -v run
```
autopkg run -v Karabiner-Elements.munki.recipe
Looking for com.github.apizz.pkg.Karabiner-Elements...
Did not find com.github.apizz.pkg.Karabiner-Elements in recipe map
Rebuilding recipe map with current working directories...
Looking for com.github.apizz.pkg.Karabiner-Elements...
Found com.github.apizz.pkg.Karabiner-Elements in recipe map
Looking for com.github.apizz.download.Karabiner-Elements...
Found com.github.apizz.download.Karabiner-Elements in recipe map
**load_recipe time: 0.006343083001411287
Processing Karabiner-Elements.munki.recipe...
WARNING: Karabiner-Elements.munki.recipe is …
```
=> Update Karabiner-Elements Recipes

Wacom/WacomTablet.munki.recipe
Since version 6.4.4, Wacom has included an "Enterprise Mode" feature that enables some configurations useful for Mac admins, most notably the suppression of the automatic app launch behavior previously seen during installations or upgrades. This represents a huge improvement in user experience, and helps avoid unexpected disruptions caused by background installations or updates.
Credit to kacey3 on Jamf Nation for discovering this XML option: https://community.jamf.com/t5/jamf-pro/how-to-disable-auto-launching-quot-wacom-desktop-center-quot-app/m-p/324051/highlight/true#M278694
=> Enable Enterprise Mode for Wacom Tablet installations

Epson/EpsonScannerDriverandScanUtility-NewCert.download.recipe
On at least one current download page (V850), a driver download named "ICA Scanner Driver" appears before Epson's driver. Thus, the regex captures it instead of the desired Epson Scan software, which can also make child recipes fail. This PR adds a " to the beginning of the regex to only capture the download whose name starts with Scanner Driver.
=> Update regex for EpsonScannerDriver download recipe

Dragonframe/DragonframeLicenseServer.download.recipe
The /download page now seems to require a user-agent.
Verbose recipe run:
```
% autopkg run -vvq 'Dragonframe/DragonframeLicenseServer.download.recipe'
Processing Dragonframe/DragonframeLicenseServer.download.recipe...
WARNING: Dragonframe/DragonframeLicenseServer.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': '(\\/download\\/DragonframeLicenseManager_(?P<version>[\\d\\.]+)\\.pkg)',
'request_headers': {'user-agent': 'Mozilla/5.0 (Macintosh; Intel '
'Mac OS X 10_15_7) '
'AppleWebKit/537.36 (KHTML, like '
'Gecko) Chrome/131.0.0.0 '
'Safari/537.36'},
'url': 'https://www.dragonframe.com/downloads/'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match …
```
=> Add user-agent to Dragonframe License Manager download

Gapminder_Offline/GapminderOffline.download.recipe
This PR fixes the Gapminder Offline download recipe using URLTextSearcher to grab the version and latest URL.
Although there are Intel and Apple Silicon versions available, this recipe grabs the Universal version suitable for either.
Verbose run output:
```
% autopkg run -vvq 'Gapminder_Offline/GapminderOffline.download.recipe'
Processing Gapminder_Offline/GapminderOffline.download.recipe...
WARNING: Gapminder_Offline/GapminderOffline.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': 'href="(https://s3-eu-west-1\\.amazonaws\\.com/gapminder-offline/Gapminder\\+Offline-(?P<version>[\\d\\.]+)-universal\\.dmg)"',
'result_output_var_name': 'url',
'url': 'https://www.gapminder.org/tools-offline/'}} …
```
=> Use URLTextSearcher for downloading Gapminder Offline

Midas_M32/MidasM32Edit.download.recipe
This PR fixes the M32Edit download, using the same rest API as the downloads page.
Verbose recipe run output:
```
% autopkg run -vvq 'Midas_M32/MidasM32Edit.download.recipe'
Processing Midas_M32/MidasM32Edit.download.recipe...
WARNING: Midas_M32/MidasM32Edit.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': '"(https://mediadl\\.musictribe\\.com/[\\S/]+/M32-Edit_MAC_[\\d\\.]+\\.zip)"',
'result_output_var_name': 'url',
'url': 'https://www.midasconsoles.com/.rest/musictribe/v1/downloadcenter/solr-dldatatable?brandName=midas&showLegacy=true&modelCode=0603-AEP&type=Software&subtype=Mac&sEcho=60&iColumns=6&iDisplayStart=0&iDisplayLength=60&mDataProp_0=modelName&sSearch_0=&bRegex_0=false&bSearchable_0=true& …
```
=> Use download rest API for retrieving latest M32Edit

SMART_Utility/SMARTUtility.download.recipe, SMART_Utility/SMARTUtility.pkg.recipe
This PR simplifies the SMARTUtility pkg recipe by switching to an existing download recipe in flammable-recipes as a parent, and deprecates the non-functional SMARTUtility download recipe in this repo.
Verbose recipe run output:
```
% autopkg run -vvq 'SMART_Utility/SMARTUtility.pkg.recipe'
Processing SMART_Utility/SMARTUtility.pkg.recipe...
WARNING: SMART_Utility/SMARTUtility.pkg.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
SparkleUpdateInfoProvider
{'Input': {'alternate_xmlns_url': 'https://www.andymatuschak.org/xml-namespaces/sparkle',
'appcast_url': 'https://www.volitans-software.com/stats/smart-utility/profileInfo.php'}}
SparkleUpdateInfoProvider: Items in feed: 1
SparkleUpdateInfoProvider: Items in default channel: 1 …
```
=> Clean up and fix SMART Utility recipes

TeacherGaming/TeacherGaming.download.recipe
This PR deprecates the TeacherGaming recipes, because the software is no longer available for download ([details](https://teachergaming.com/)).
=> Deprecate TeacherGaming recipes

OpenKiosk/OpenKiosk.download.recipe
This PR updates the file pattern used to download OpenKiosk.
I notice the old pattern captured `version` and `date` variables but didn't do anything with them, so I left them out for simplicity.
Verbose recipe run output:
```
% autopkg run -vvq 'OpenKiosk/OpenKiosk.download.recipe'
Processing OpenKiosk/OpenKiosk.download.recipe...
WARNING: OpenKiosk/OpenKiosk.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': 'https://www\\.mozdevgroup\\.com/dropbox/okcd/\\d+/release/OpenKiosk[\\d\\.-]+-universal\\.dmg',
'result_output_var_name': 'url',
'url': 'https://openkiosk.mozdevgroup.com/'}}
URLTextSearcher: Found matching text (url): https://www.mozdevgroup.com/dropbox/okcd/115/release/OpenKiosk115.18.0-2024-1 …
```
=> Update file pattern for OpenKiosk download

RedisInsight/RedisInsight.download.recipe, RedisInsight/RedisInsight.pkg.recipe
This PR adjusts the download URL and app name for Redis Insight.
Verbose recipe run output with default (Intel) architecture:
```
% autopkg run -vvq 'RedisInsight/RedisInsight.download.recipe'
Processing RedisInsight/RedisInsight.download.recipe...
WARNING: RedisInsight/RedisInsight.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
{'Input': {'filename': 'RedisInsight.dmg',
'url': 'https://s3.amazonaws.com/redisinsight.download/public/latest/Redis-Insight-mac-x64.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new Last-Modified header: Fri, 27 Dec 2024 14:10:12 GMT …
```
=> Adjust download URL and app name for Redis Insight recipes

Stage_Plot_Pro/StagePlotPro-XPlace.download.recipe, Stage_Plot_Pro/StagePlotPro.download.recipe
Searching around the net reveals that many people are having issues downloading StagePlotPro or getting in touch with the developer. The app is likely no longer being developed.
This PR deprecates the StagePlotPro recipes.
=> Deprecate StagePlotPro recipes

BlockBlock/BlockBlock.pkg.recipe, GAM/GAM.pkg.recipe, HashiCorp/Vault.pkg.recipe, Sqwarq/CriticalUpdates.pkg.recipe, Sqwarq/FastTasks2.pkg.recipe, SwiftDefaultApps/SwiftDefaultApps.pkg.recipe, SwiftDefaultApps/SwiftDefaultApps_CLI.pkg.recipe, Turbo_Boost_Switcher/TurboBoostSwitcher.pkg.recipe, Unity/Unity3DDocumentation.pkg.recipe, defaultbrowser/defaultbrowser.pkg.recipe, jamJAR/jamJAR.pkg.recipe, unearth/unearth.pkg.recipe
Hundreds of recipes dating from the very beginning of AutoPkg use the `options` key in the `pkg_request` argument of PkgCreator:
```xml
<key>options</key>
<string>purge_ds_store</string>
```
However, this key doesn't serve any purpose at all. The `options` key is ignored and not passed along to `pkgbuild`, regardless of its presence or contents. It appears that this has been the case since the very first public release of AutoPkg 0.1.0!
So this pull request (one of over 100) formally ends this practice and removes the unused and unneeded `options` key from all recipes in the AutoPkg org that use PkgCreator.
Thanks for considering!
_This PR was submitted using [Repo Lasso](https://github.com/homebysix/repo-lasso) v1.2.0._
=> Removal of unused `options` from PkgCreator arguments
